### ISSUE TITLE
What if a user makes a mistake while updating his email?

### ISSUE THREAD

**Issue by wouterdorgelo** [JonVadar/Laravel_Listing_App#2]
Let's say a user tries to update his email address but makes a mistake and enters a wrong email address. The app already changes the current email address to the new one in the database before it's verified. So, if the user can not verify the new email address because he made a mistake, he can't enter his account anymore. I think the solution is an extra database field `pending_email`, which stores the pending email until it's verified.

**Comment by JonVadar** [comment]
If I, the user, enter a wrong email and subsequently don't have access to that email, I can simply change it back to my correct/valid email and verify it.
